name: Terraform Deployment Workflow

on:
  push:
    branches:
      - main
      - '**'

jobs:
  terraform:
    name: Run Terraform Commands
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan or Apply
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            terraform apply -auto-approve
          else
            terraform plan
          fi
